/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c6c6c6",
        "primary": "#506600",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed": "#e2e2e2",
        "tertiary": "#5d5f5f",
        "secondary": "#5e5e5e",
        "on-primary-fixed": "#161e00",
        "inverse-primary": "#b1d446",
        "tertiary-container": "#b8b9b9",
        "surface-tint": "#506600",
        "surface-container-low": "#f3f3f3",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1b1b1b",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#757965",
        "surface": "#f9f9f9",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b1d446",
        "error": "#ba1a1a",
        "on-primary-container": "#3e5000",
        "primary-fixed": "#ccf05f",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-fixed": "#e2e2e2",
        "on-surface-variant": "#454937",
        "surface-dim": "#dadada",
        "outline-variant": "#c5c9b1",
        "on-secondary-container": "#646464",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed-variant": "#474747",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#a4c639",
        "surface-container": "#eeeeee",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3c4d00",
        "secondary-container": "#e2e2e2",
        "background": "#f9f9f9",
        "on-tertiary-container": "#484a4a",
        "inverse-surface": "#2f3131"
      },
      fontFamily: {
        "brand": ["Unbounded", "Outfit", "Space Grotesk", "sans-serif"],
        "display": ["Syne", "Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "button-text": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "unit": "4px",
        "margin-desktop": "64px"
      },
    },
  },
  plugins: [],
}
