const express = require('express');
const cors = require('cors');
const multer = require('multer');
const { v4: uuidv4 } = require('uuid');
const path = require('path');
const fs = require('fs');
const db = require('./database');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Configure Multer for file uploads
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, path.join(__dirname, 'uploads'));
  },
  filename: function (req, file, cb) {
    // Generate a unique filename for the physical file
    const uniqueName = uuidv4() + '.chuchudu';
    cb(null, uniqueName);
  }
});

const upload = multer({ storage: storage });

// POST /api/shares
app.post('/api/shares', upload.single('file'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const { fileName, mimeType, size } = req.body;
    
    // The physical filename generated by multer
    const fileId = req.file.filename; 
    
    // The public token UUID
    const id = uuidv4(); 
    
    // Default expiration: 24 hours from now
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

    const sql = `INSERT INTO shares (id, file_id, file_name, mime_type, size, expires_at) VALUES (?, ?, ?, ?, ?, ?)`;
    
    db.run(sql, [id, fileId, fileName, mimeType, size, expiresAt], function(err) {
      if (err) {
        console.error(err);
        return res.status(500).json({ error: 'Database error' });
      }
      
      res.status(201).json({ id, expiresAt });
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// GET /api/shares/:id
app.get('/api/shares/:id', (req, res) => {
  const { id } = req.params;
  
  db.get(`SELECT id, file_name, mime_type, size, created_at, expires_at FROM shares WHERE id = ?`, [id], (err, row) => {
    if (err) {
      console.error(err);
      return res.status(500).json({ error: 'Database error' });
    }
    
    if (!row) {
      return res.status(404).json({ error: 'Share not found' });
    }
    
    // Check expiration
    if (new Date(row.expires_at) < new Date()) {
      return res.status(410).json({ error: 'Share has expired' });
    }
    
    res.json(row);
  });
});

// GET /api/shares/:id/download
app.get('/api/shares/:id/download', (req, res) => {
  const { id } = req.params;
  
  db.get(`SELECT file_id, expires_at FROM shares WHERE id = ?`, [id], (err, row) => {
    if (err) {
      console.error(err);
      return res.status(500).json({ error: 'Database error' });
    }
    
    if (!row) {
      return res.status(404).json({ error: 'Share not found' });
    }
    
    // Check expiration
    if (new Date(row.expires_at) < new Date()) {
      return res.status(410).json({ error: 'Share has expired' });
    }
    
    const filePath = path.join(__dirname, 'uploads', row.file_id);
    
    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: 'File not found on server' });
    }
    
    res.setHeader('Content-Type', 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="${row.file_id}"`);
    
    const fileStream = fs.createReadStream(filePath);
    fileStream.pipe(res);
  });
});

app.listen(PORT, () => {
  console.log(`ChuChudu Backend Server running on http://localhost:${PORT}`);
});
